Enable analysis caching codepaths only for commands that execute actions.
For example, this includes `test` and `build`, but does not include `cquery`.

This prevents the use case where the someone adds `build
--experimental_remote_analysis_cache_mode=download` by default into their
bazelrc, and runs a cquery command (which, WAI, picks up the flag, because
`CqueryCommand` inherits options from `TestCommand`, which inherits from
`BuildCommand`), and fails to this cryptic error:

```
$ bazel cquery 'somepath(//foo, //bar)'
ERROR: Failed to find PROJECT.scl file for: [//foo:foo, //bar:bar]
INFO: Elapsed time: 0.078s
ERROR: Build did NOT complete successfully
```

It also doesn't make sense to support analysis caching with cquery anyway, because correct results require a complete, unpruned analysis graph.

Same goes for `aquery`.

PiperOrigin-RevId: 689397164
Change-Id: Ib63ab41450b84e782d69e148196b2bfa6413e65f